#Data
BASE_DATA_FOLDER = 'Data/MyDataset'
DATA_PATH = BASE_DATA_FOLDER + '/' + 'images'
RECOGNIZE_CLASS = 'Samsung'
OTHERS_CLASSES = 'Others'
LABELS_PATH = BASE_DATA_FOLDER + '/' + 'labels.txt'

#Gen
NUM_FILES = 20
IMAGE_KERNEL = 11
MAX_SHIFT = 20
COMBINED_SIZE = 150
MAX_OPS = 3

#Tensorflow
VAL_PERCENT = 0.1
TEST_PERCENT = 0.2
RANDOM_SEED = 42
SAVE_FOLDER = 'Artifacts/Models'
BATCH_SIZE = 32

#Model
EPOCHS = 25
DEFAULT_LR = 0.0001

#Image
IMAGE_WIDTH = 299
IMAGE_HEIGHT = 299